### ISSUE TITLE
Support for groq

### ISSUE THREAD

**Issue by Pascal1132** [lofcz/LlmTornado#22]
It will be insane if we can add support for groq.com's API.

**Comment by lofcz** [comment]
This should be already possible as Groq is OAI compatible - https://console.groq.com/docs/openai
If you are interested in the feature I can add a demo showing how to do that soon.

**Comment by lofcz** [comment]
@Pascal1132 groq models are now supported in 3.1.5
Here are all chat models from groq running in LLM Tornado:
![image](https://github.com/user-attachments/assets/c8e360d6-149b-4062-a729-9f71478fb7cc)
