### ISSUE TITLE
Claude Sonnet 3.5, OpenAI GPT4o mini, Azure Gpt4o mini

### ISSUE THREAD

**Issue by drkhateeb** [lofcz/LlmTornado#23]
Hello dear devs

kindly update the tornado to these models

Claude Sonnet 3.5, OpenAI GPT4o mini, Azure Gpt4o mini

This is the place where we develop and maintain most of SDL's plugins for Trados Studio. If you want to help us or just looking for some examples this is the perfect place

https://github.com/RWS/Sdl-Community

integrate Tornado in this plugin 
https://github.com/RWS/Sdl-Community/tree/master/GoogleCloudTranslationProvider

this will bring translation from LLMs

best

**Comment by lofcz** [comment]
Claude 3.5 and Gpt4o mini are already supported.
